/**
 * Landing "who it's for" band.
 *
 * The Hero says what the platform does; this band says who it's for, in the
 * three vocabularies that matter for a contract-analysis product: the counsel
 * who has to trace every term, the quant who has to model the numbers, and the
 * engineer who has to wire it into their own stack. Each column speaks that
 * audience's language deliberately — traceability / verifiable computation /
 * open protocols.
 *
 * Shared, copy-as-code (same pattern as `BRANDING.demo.pillars`): the columns
 * are a deploy-time constant, not env-driven. The product name is the only
 * brand-variable token, read from `BRANDING.appName`. A fork retargeting a
 * different audience patches the `AUDIENCES` array in this file.
 */
import { BRANDING } from "@/lib/branding";

interface Audience {
  key: string;
  /** Who they are — the chip label. */
  role: string;
  /** The headline promise, in their words. */
  headline: string;
  /** One sentence of substance, not marketing. */
  body: string;
}

function audiences(appName: string): Audience[] {
  return [
    {
      key: "counsel",
      role: "Technical counsel",
      headline: "Trace every term to its clause",
      body: "Every extracted obligation links back to the exact line it came from — page, section, verbatim text. No paraphrase, no invented term, nothing to take on trust.",
    },
    {
      key: "quants",
      role: "Quants & structurers",
      headline: "Numbers you can verify to the euro",
      body: "Settlement, indexation and liquidated-damages what-ifs are computed deterministically from the extracted terms — recomputed in milliseconds, not generated by a model.",
    },
    {
      key: "engineers",
      role: "AI & legal engineers",
      headline: "Build on open protocols",
      body: `Skills, A2UI surfaces and MCP tools over Google ADK. Extend ${appName}, add your own tools, and run it on your own cloud — the contract never leaves your project.`,
    },
  ];
}

export function AudienceBand() {
  const items = audiences(BRANDING.appName);
  return (
    <section className="mx-auto w-full max-w-7xl px-6 py-16 md:px-10 md:py-20">
      <div className="mb-8 flex items-end justify-between">
        <h2 className="font-mono text-[10px] uppercase tracking-[0.25em] text-muted-foreground">
          Built for the people who read the contract
        </h2>
      </div>
      <ul className="grid grid-cols-1 gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-3">
        {items.map((a, i) => (
          <li
            key={a.key}
            className="group relative flex flex-col gap-3 bg-background p-6"
          >
            <div className="flex items-center gap-2">
              <span className="font-mono text-[10px] tabular-nums text-primary">
                {String(i + 1).padStart(2, "0")}
              </span>
              <span className="inline-flex items-center rounded-full border border-primary/25 bg-primary/5 px-2.5 py-0.5 font-mono text-[10px] uppercase tracking-[0.14em] text-primary">
                {a.role}
              </span>
            </div>
            <h3 className="text-lg font-semibold leading-snug tracking-tight text-foreground">
              {a.headline}
            </h3>
            <p className="text-sm leading-relaxed text-muted-foreground">
              {a.body}
            </p>
          </li>
        ))}
      </ul>
    </section>
  );
}
